apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orbitflow
  namespace: monitoring
  labels:
    release: monitoring   # 🔥 이 줄이 핵심
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: orbitflow
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s